### ISSUE TITLE
Error: the parameter 'vcf.file.genome' should be supported by BSgenome.

### ISSUE THREAD

**Issue by V-Catherine** [cgab-ncc/FIREVAT#10]
Hello,
I'm trying to run Firevat on a vcf from Mutect2 with genome="hg38" but I get the following error:
```
Error in RunFIREVAT(vcf.file = sample.vcf.file, vcf.file.genome = "hg38",  : 
  The parameter 'vcf.file.genome' should be supported by BSgenome.
```
I've downloaded with success hg38 using the following command:
`BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")`
Do you have any idea what the problem is ?
Thanks for your help
Catherine

**Comment by SilenWang** [comment]
I ran into the same issue. Use ''BSgenome.Hsapiens.UCSC.hg38'' instead of "hg38" solve the problem.

**Comment by SilenWang** [comment]
> I ran into the same issue. Use ''BSgenome.Hsapiens.UCSC.hg38'' instead of "hg38" solve the problem.

Well, doing so will cauese downstream problem. It seems that version 0.6.0 change the way to tell if the input genome is wrong, and this cause the problem.

I think you can either edit  the downloaded source code to repair this or reinstall an older version.

**Comment by V-Catherine** [comment]
Thanks for your input

**Comment by khb7840** [comment]
Sorry for late reply because this bug was due to the updates of BSgenome.
FIREVAT checks the input genome is available for BSgenome and the name of vector for available genome version has been changed from "provider_version"(2017) to "genome" (2021). 
I'll upload a hotfix today.

ver 1.42.0 (2017)
![Screen Shot 2021-03-16 at 5 15 59 PM](https://user-images.githubusercontent.com/21071189/111277205-84ad9580-867b-11eb-99d6-7e472355013e.png)

ver 1.58.0 (2021)
![Screen Shot 2021-03-16 at 5 15 40 PM](https://user-images.githubusercontent.com/21071189/111277174-7cedf100-867b-11eb-8345-eca8d00a7439.png)

**Comment by V-Catherine** [comment]
Thanks! This solves the issue :-)
